### ISSUE TITLE
Sequence Logic App Workflow deployment to get callback url 

### ISSUE THREAD

**Issue by uday31in** [Azure/ai-hub#165]
VideoIndexer-Workflow needs callback url from Callback-Workflow

<img width="1095" alt="image" src="https://github.com/Azure/ai-hub/assets/14359777/e7ad410e-9624-4f3a-a13a-597d6c6bc88c">

**Comment by marvinbuss** [comment]
Addressed by https://github.com/Azure/ai-hub/pull/166
