### ISSUE TITLE
Required enhancements for On Your Data scenario

### ISSUE THREAD

**Issue by victorar** [Azure/ai-hub#225]
Include the following enhancements for the On Your Data scenario within the reference implementation:

- In ADF, ensure output from Document Intelligence is preserved in markdown (and not in .txt) via a data flow.
- Make sure the following containers are created in the storage account: curated, docsbatch and docsintelbatch.
- Remove the docs and docsintel containers from storage account.
- In ADF, remove triggers for single file upload and single file upload with docIntel.
- In ADF, ensure AOAI On Your Data ingestion job is only executed one (for index and indexer creation).
- In ADF, implement pipelines for batchAnalyzeDocuments and batchAnalyzeDocuments_withoutIntel.
- Ensure triggers (based on Schedules) are implemented for the two pipelines described in the previous step.

**Comment by esbran** [comment]
Add a dataflow called createMDfile. Either an empty flow and I can fill in the code or I can share the code.
Add parameter for dataRefreshIntervalInMinutes - dynamic int value
Add parameter for chunkSize - dynamic int value
Add parameter for batch - hard bool coded value

Replace code for all pipelines

**Comment by victorar** [comment]
Resolved via #229 , #230, #231, #232 , #233 , #234 and #235
